config/routes.rb
CheapTaps::Application.routes.draw do

  resources :venues do
    resources :deals
  end

  devise_for :users

  root :to => 'application#index'

end

app/models/deal.rb
class Deal
  include Mongoid::Document
  field :name, type: String, default: ""
  field :date, type: Time
  field :start_time, type: Time, default: ""
  field :end_time, type: Time, default: ""
  field :recurring, type: Boolean

  #validation
  attr_accessible :name, :date, :start_time, :end_time, :recurring
  validates_presence_of :name, :date, :start_time, :end_time

  # relationships
  belongs_to :user
  belongs_to :venue
end

app/models/user.rb
class User
  include Mongoid::Document

  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  # user personal stuff
  field :name, type: String, default: ""

  #validation
  validates_presence_of :name, :email, :encrypted_password
  validates_uniqueness_of :name, :email, case_sensitive: false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  # admin
  field :admin, :type => Boolean, :default => "false"

  # relationships
  has_many :deals
end

app/models/venue.rb
class Venue
  include Mongoid::Document
  # field :foursquare_api_id, String
  field :name
  field :street_address
  field :city
  field :state
  field :country
  field :mail_code #this seems like a nice compromise on the zip/postal code thing
  field :lat
  field :long




  has_many :deals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @deals = []
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :get_deal_from_params_id, :only => [:edit, :show, :create, :update, :destroy]
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

  private

    def get_deal_from_params_id
      @deal = Deal.find(params[:id])
    end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_filter :get_venue_from_params_id, :only => [:edit, :show, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @venues }
    end
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/new
  # GET /venues/new.json
  def new
    @venue = Venue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @venue }
    end
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(params[:venue])
    
    respond_to do |format|
      if @venue.save
        format.html {redirect_to @venue, notice: 'Venue was successfully created.'}
        format.json { render json: @venue, status: :created, location: @venue }
      else
        format.html { render action: "new" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /venues/1
  # PUT /venues/1.json
  def update

    respond_to do |format|
      if @venue.update_attributes(params[:venue])
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy

    respond_to do |format|
      format.html { redirect_to venues_url }
      format.json { head :no_content }
    end
  end
end

  private

    def get_venue_from_params_id
      @venue = Venue.find(params[:id])
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/application/index.html.haml
 
/
  .row
    .span9
      .sponsored-deal.deal
        = render "deals/sponsored"
      .map
        =# image_tag "http://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=700x400&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Ccolor:red%7Clabel:C%7C40.718217,-73.998284&sensor=false"
      .list
        - 10.times do
          = render "deals/deal"

    .span3
      .top-contributors
        %h3 In the know
        - 3.times do
          %section.contributor
            .bling.pull-right
              .total 999
              .badges badges
            %h1 User Name

app/views/deals/_deal.html.haml
%section.deal{itemscope: true, itemtype: "http://schema.org/Offer"}

app/views/deals/_form.html.haml
= simple_form_for @deal do |f|
  = f.input :name, label: "What's the deal?", required: true
  = f.input :date, label: "When is it?", input_html: {class: "datepicker"}, wrapper_html: {class: "datepicker-wrap"}, required: true
  = f.input :start_time, label: "Starts at:", input_html: {type: "time", class: "time-scroller"}, wrapper_html: {class: "time-picker-wrap"}, required: true
  = f.input :end_time, label: "Ends at:", input_html: {type: "time", class: "time-scroller"}, wrapper_html: {class: "time-picker-wrap"}, required: true
  = f.input :recurring, as: :boolean, label: "Every week?"
  = f.input :venue_id, as: :hidden, input_html: {value: params[:venue_id]}
  = f.submit 'Save', class: "btn btn-primary"

app/views/deals/_sponsored.html.haml
%section
  .pull-right
    .up-votes Good Deal: +9
  %h1 5 dollar pints at Osum Bar
  %time 5pm-7pm
  .venue= link_to "Osum Bar", "#"

app/views/deals/edit.html.haml
%h1 Editing deal

= render 'form'

= link_to 'Show', @deal
\|
= link_to 'Back', deals_path

app/views/deals/index.html.haml
%h1 Listing deals

%table
  %tr
    %th
    %th
    %th

  - @deals.each do |deal|
    %tr
      %td= link_to 'Show', deal
      %td= link_to 'Edit', edit_venue_deal_path(deal)
      %td= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Deal', new_venue_deal_path

app/views/deals/new.html.haml
%h1 New deal

= render 'form'

app/views/deals/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_deal_path(@deal)
\|
= link_to 'Back', deals_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Arvo"
    = stylesheet_link_tag "application", media: "all"
    %meta{ :"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }
    %meta{:name => "viewport", :content => "width=device-width"}
    %title Cheap Taps! Find deals on drinks near you
    = csrf_meta_tags
  %body{class: "#{controller_name} #{action_name}"}
    = render partial: "users/sidebar"
    .non-sidebar-container
      = render partial: "shared/header"
      = render partial: "shared/flashes"
      #map
      .container= yield
  = javascript_include_tag "require.min", "data-main" => "/assets/main"

app/views/shared/_flashes.html.haml
- if notice.present?
  .alert.alert-success
    %button.close{"data-dismiss" => "alert", :type => "button"} x
    = notice
- if alert.present?
  .alert.alert-error
    %button.close{"data-dismiss" => "alert", :type => "button"} x
    = alert

app/views/shared/_header.html.haml
%header.navbar.ct-navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "cheapTAPS", root_path, class: "brand pull-left"
      - if user_signed_in?
        %ul.nav.nav-pills.pull-right
          %li
            = link_to venues_path do #user needs to find the venue for the deal first
              %i.icon-plus-sign
              Add A Deal
          = render "shared/user_name"
      #header-tag
        Find beer deals near
        #current-location-human

app/views/shared/_user_name.html.haml
- if user_signed_in?
  %li.current-user= link_to current_user.name, "#"
  %li.sign-out= link_to "Sign out", destroy_user_session_path
- else
  %li.sign-up= link_to "Sign up", new_user_registration_path
  %li.sign-in= link_to "Sign in", new_user_session_path

app/views/users/_caps.html.haml
caps

app/views/users/_sidebar.html.haml
#user-sidebar
  =#debug(current_user)

app/views/venues/_form.html.haml
= simple_form_for @venue, class: "form-horizontal" do |f|
  = f.input :name
  = f.input :street_address
  = f.input :city
  = f.input :state
  = f.input :country
  = f.input :mail_code #this seems like a nice compromise on the zip/postal code thing
  = f.input :lat
  = f.input :long
  = f.button :submit, "Save Venue"

app/views/venues/edit.html.haml
%h1 Editing venue

= render 'form'

= link_to 'Show', @venue
\|
= link_to 'Back', venues_path

app/views/venues/index.html.haml
%h1 Where Is This Deal?
%p here, we want the map pins to show the local bars, user clicks on the pin, and the bubble has a button to add a new deal
%p In case the venue isn't on the map (like if they're rural), have a link to add a venue:
= link_to "Add A Venue", new_venue_path, class: "btn btn-large"

app/views/venues/new.html.haml
%h1 Add A Venue
%p here, we first ask the user to use their mobile location 
venue name
%br
use my location
%br
if you aren't mobile, or you want to get super specific, use this form:
= render "form"

app/views/venues/show.html.haml
%h1 venue name
%p here, we can list all the deals at this venue irrespective of the date (i.e. we don't care that the deal is for next tuesday here)
= link_to "Add A New Deal", new_venue_deal, class: "btn btn-large"

= link_to 'Edit', edit_venue_path(@venue)
\|
= link_to 'Back', venues_path